apiVersion: v1
kind: Service
metadata:
  name: {{ include "iceberg-rest.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app: {{ include "iceberg-rest.name" . }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}